# Generated by Django 5.0.7 on 2024-09-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='escola',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gestao.escola', verbose_name='Escola'),
            preserve_default=False,
        ),
    ]
